"""Template for the standalone E2E tutorial notebook (consumed by ``tools/build_notebook.py``).

Numbers quoted in the prose are the package-API build record of 2026-09-20 (RTX 5070 Ti, seed 0) on the
pinned 1,600 / 200 / 400 promoter sample; the generated notebook re-measures all of them.
"""

# ruff: noqa: E501

TEMPLATE = {
    "package": "nucleotide_transformer_genomics_pipeline",
    "repo_name": "nucleotide-transformer-genomics-pipeline",
    "stem": "nucleotide_transformer",
    "notebook_name": "nucleotide_transformer_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "pipeline_class": "NucleotideTransformerPipeline",
    "weights_key": "nt-v2-50m-multi-species",
    "modules": ["pipeline.py", "metrics.py", "samples.py"],
    "runtime_imports": ["torch", "transformers"],
    "title": "Nucleotide Transformer v2 50M — DIMER E2E promoter fine-tuning tutorial (standalone)",
    "badges": [
        ("GitHub", "https://img.shields.io/badge/GitHub-nucleotide--transformer--genomics--pipeline-181717?logo=github", "https://github.com/kurtvalcorza/nucleotide-transformer-genomics-pipeline"),
        ("Model card", "https://img.shields.io/badge/Model%20card-MODEL__CARD.md-blue", "https://github.com/kurtvalcorza/nucleotide-transformer-genomics-pipeline/blob/main/MODEL_CARD.md"),
        ("Licence", "https://img.shields.io/badge/weights-CC%20BY--NC--SA%204.0-orange", "https://creativecommons.org/licenses/by-nc-sa/4.0/"),
        ("Upstream", "https://img.shields.io/badge/Hugging%20Face-InstaDeepAI%2Fnucleotide--transformer--v2--50m--multi--species-yellow", "https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-50m-multi-species"),
    ],
    "model_cell_note": (
        "There is no fallback to a different download. **This checkpoint ships its own model code**, and the manifest lists "
        "the two Python files the loader executes (`modeling_esm.py`, `esm_config.py`), so `verify_snapshot` has re-hashed "
        "them before `from_pretrained` imports them with `trust_remote_code=True` — the tokenizer loads natively with "
        "`trust_remote_code=False`. Digest verification proves the executed code is the pinned upstream code byte for byte; "
        "it is not a safety claim about that code, and this is the one row of the fleet where remote code runs at all "
        "(accepted for this row on 2026-09-20)."
    ),
    "capability": "DNA sequence representation (one 512-d mean-pooled vector per sequence) and bounded supervised fine-tuning of a promoter classifier — a mean-pooled head plus the last two encoder blocks — on labelled `{id, sequence, label}` records, using the pinned `InstaDeepAI/nucleotide-transformer-v2-50m-multi-species` weights (CC BY-NC-SA 4.0)",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime installs the pinned dependencies, stages and digest-verifies the "
        "pinned `InstaDeepAI/nucleotide-transformer-v2-50m-multi-species` snapshot (a 224 MB `model.safetensors` and the two "
        "model-code files, all re-hashed before the code is imported), reads the 2,200-sequence human promoter sample that is "
        "carried **inline** in the package (no data download at all), validates and splits it 1,600 / 200 / 400 without "
        "leakage, embeds a few sequences and predicts a masked 6-mer through the inference contract with an input manifest and "
        "a rejection probe, scores two non-neural baselines and a logistic probe on the **frozen** embeddings over the 400 "
        "held-out sequences, runs a bounded fine-tuning of the mean-pooled head plus the last two encoder blocks with "
        "cross-entropy and epoch selection on validation MCC, scores the held-out sequences again, exports the adapter as "
        "safetensors with a manifest, and reloads that artifact into a fresh pipeline to verify prediction parity. The "
        "default path needs no repository clone, no DIMER worker or service, no credential, no upload dialog and no "
        "configuration edit (NOTEBOOK_SPEC 2.0 §5). On an RTX 5070 Ti the fine-tuning took 34 s and the whole path about two "
        "minutes after the snapshot download; every sequence is 47 tokens long, so CPU is workable — a CUDA runtime is used "
        "automatically when present."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4 and re-run from that cell to upload one "
        "CSV with a header naming `sequence` and `label` (0/1; an optional `id`) — at least eight sequences of 12..6,000 "
        "A/C/G/T/N bases with both labels present. The records pass through the same validation, sequence-disjoint split, "
        "baselines, frozen probe, fine-tuning, held-out evaluation, artifact export and reload-parity cells as the promoter "
        "sample. Uploaded files stay inside this runtime. BYOD is optional and never part of the default path."
    ),
    "intro": (
        "`InstaDeepAI/nucleotide-transformer-v2-50m-multi-species` is the smallest Nucleotide Transformer v2 (Dalla-Torre et "
        "al., 2024): a 12-block, 512-wide encoder with rotary positions and a bias-free SwiGLU feed-forward, pre-trained by "
        "masked 6-mer prediction on 850 genomes (55,904,972 parameters as loaded with its masked-LM head; the encoder alone "
        "is 53,534,401). Its weights are published under **CC BY-NC-SA 4.0** — attribution, **non-commercial**, share-alike — "
        "and every embedding, probe and adapter below inherits those conditions. The checkpoint cannot be loaded by the "
        "native Transformers ESM classes (its `config.json` carries an `auto_map` and the native block has no bias-free "
        "SwiGLU), so it ships its own `modeling_esm.py`; Section 3 verifies that file's digest before it is imported.\n\n"
        "What this notebook adds to representation is **adaptation with labelled sequences**. The task is the human "
        "non-TATA promoter benchmark of Genomic Benchmarks: 251-base windows of the GRCh38 reference that either centre on "
        "a promoter from the Eukaryotic Promoter Database or contain none. Promoters are GC-rich, so the composition-only "
        "baseline is not trivial — a single GC threshold fitted on the training split scores **0.715** accuracy / MCC 0.431 "
        "on the 400 held-out windows — and a logistic probe on the *frozen* mean-pooled embeddings already reaches 0.815 / "
        "0.632. So the honest question is narrow: does a bounded fine-tuning of a small mean-pooled head plus the last two "
        "encoder blocks (8,660,482 of 53.8 M parameters) on 1,600 windows move the held-out **MCC** past the frozen probe "
        "and both baselines? The build record measured 0.8425 / **0.693** — a gain of 0.06 MCC over the frozen probe on one "
        "seeded draw. Nothing here is a claim about your sequences: it is one split of one benchmark's labelling convention.\n\n"
        "**Snapshot note:** the pinned revision ships `model.safetensors` (an 8-file manifest: weights, config, tokenizer "
        "files, README and the two model-code files); the upstream repository also hosts a `pytorch_model.bin` and a JAX "
        "checkpoint, which are not in the manifest and are never staged or loaded, so no pickle is opened anywhere. The "
        "adapter written in Section 9 is safetensors too."
    ),
    "learning_objectives": (
        "install the pinned runtime; read what the carried package guarantees, including where its remote-code perimeter "
        "begins and ends; stage and digest-verify the immutable upstream snapshot; read a digest-pinned, licence-traced "
        "promoter sample carried inline, validate it and split it without leakage; embed sequences and predict a masked 6-mer "
        "through the public API and read the output contract correctly (a representation is not a prediction; the masked "
        "distribution is the pre-training objective, not a classifier); measure two non-neural baselines and a logistic "
        "probe on the frozen embeddings; run a bounded fine-tuning of a mean-pooled head plus the last two blocks with a "
        "stated loss, explicit hyperparameters and validation-based epoch selection; evaluate on a sequence-disjoint test "
        "split with accuracy and MCC; and export a safetensors adapter that reloads against the pinned base with verified "
        "parity and carries the base licence with it."
    ),
    "exclusions": (
        "multi-class or multi-label genomics tasks, token-level prediction (splice sites, variant effects), sequences longer "
        "than 6,000 bases, generation, fine-tuning of the embeddings or of the first ten encoder blocks, LoRA, the other "
        "seventeen tasks of the Nucleotide Transformer benchmark or any benchmark proper (only one seeded 2,200-sequence draw "
        "of one Genomic Benchmarks task is scored here), calibration of the class probabilities, and any claim that a "
        "promoter classifier transfers to other regulatory elements or other species. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Runtime:** a fresh supported runtime (Google Colab or Jupyter, Python 3.12). The default path runs on CPU (float32) and uses CUDA automatically when available. Every sequence is 251 bases = 47 tokens, so the model is cheap per step: the build record measured 3 s for the frozen probe and 34 s for the six-epoch fine-tuning with per-epoch validation on an RTX 5070 Ti (558 MiB peak), and 213 s for the same fine-tuning on the build workstation's CPU (19 s for the probe). Expect a few tens of minutes on a 2-vCPU hosted runtime. The pinned `torch==2.14.0` install and the 224 MB checkpoint are the large downloads of the run; the data is carried inline.",
        "- **Knowledge:** basic Python; what a DNA sequence, GC content and a promoter are; what accuracy and Matthews correlation measure and why MCC is 0 for a constant predictor; why a probe on frozen embeddings and a fine-tuned model answer different questions.",
        "- **Data contract:** records are `{id, sequence, label}` — `sequence` a string of A/C/G/T/N of 12..6,000 bases (case-insensitive; `N` is tokenised base by base), `label` 0 or 1, `id` matching `[A-Za-z0-9_.:-]{1,64}` and unique; a dataset needs 8..20,000 records and a training split needs both labels; splitting de-duplicates by exact sequence so no sequence lands in two splits. BYOD accepts one CSV with a header naming `sequence` and `label` (and optionally `id`).",
        "- **Validation is structural, not biological:** every sequence is checked for alphabet, length and label, but nothing checks that a label is right or that a window is a promoter — a mislabelled set is fine-tuned on without complaint.",
        "- **Licence:** the weights are **CC BY-NC-SA 4.0**. Copying, redistribution and adaptation are permitted for non-commercial purposes with attribution and under the same licence; **commercial use is not permitted under this licence**. The adapter this notebook writes is a derivative of the weights and carries the same conditions, recorded in its manifest.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there. The default path uploads nothing.",
        "- **External access (data):** none. The 2,200 sequences are carried inline in the carried `samples.py` with their digest. Their provenance is recorded there: interval lists from `ML-Bioinfo-CEITEC/genomic_benchmarks` (Apache-2.0) at commit `605d8539…` (four gzipped CSVs pinned by size and SHA-256) and bases from the GRCh38 human reference genome (Genome Reference Consortium, public domain) read through Ensembl REST; `tools/pin_sample.py` in the repository reproduces the draw from those sources and asserts the digest. Nothing is redistributed beyond 2,200 windows of a public-domain reference.",
    ],
    "cells": [
        {
            "md": (
                "## 4. The promoter sample, its provenance and the split\n\n"
                "`sample_dataset` returns the pinned draw from the inline block of the carried `samples.py` — 1,600 training, "
                "200 validation and 400 test windows, half promoter and half not in every split, the train and validation "
                "windows drawn from the origin's *train* lists and the test windows from its *test* lists — and refuses to "
                "return it unless the block still hashes to `SAMPLE_DIGEST`. Each record carries its genomic interval "
                "(chromosome, 0-based half-open start/end, strand) so any window can be looked up in the reference. "
                "`validate_dataset` checks every record against the contract (alphabet, 12..6,000 bases, label 0/1, unique "
                "ids, both labels in the training split) and reports counts, lengths, GC fractions and a digest; "
                "`check_split_disjoint` asserts no sequence appears twice; the training split's table is written to "
                "`outputs/{stem}_train.csv` (also a valid BYOD file).\n\n"
                "Look for: three digests, promoter windows with a mean GC fraction around 0.62 against 0.48 for the "
                "negatives — the composition gap the GC baseline of Section 6 lives on — and four refusal probes (a "
                "duplicate id, a base outside A/C/G/T/N, a window too short, a training split with one label) each rejected "
                "before the model does anything."
            ),
            "code": (
                "import hashlib\n"
                "import json\n"
                "import time\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "if USE_BYOD:\n"
                "    from google.colab import files\n"
                "    uploaded = files.upload()\n"
                "    file_name, payload = next(iter(uploaded.items()))\n"
                "    byod_csv = Path('work') / 'byod.csv'\n"
                "    byod_csv.parent.mkdir(parents=True, exist_ok=True)\n"
                "    byod_csv.write_bytes(payload)\n"
                "    records = load_byod_dataset(byod_csv)\n"
                "    splits = split_dataset(records, seed=SPLIT_SEED)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod': len(records)}}\n"
                "else:\n"
                "    t0 = time.perf_counter()\n"
                "    splits = sample_dataset()\n"
                "    data_source = f'{{CORPUS_NAME}}: {{CORPUS_REPO}}@{{CORPUS_REVISION[:12]}} ({{CORPUS_LICENSE}})'\n"
                "    raw_rows = {{'origin_rows': CORPUS_ROWS, 'inline_records': sum(len(v) for v in splits.values()), 'pinned_digest': SAMPLE_DIGEST[:16] + '...', 'seconds': round(time.perf_counter() - t0, 3)}}\n"
                "dataset_manifests = {{name: validate_dataset(part, require_both_labels=(name == 'train')) for name, part in splits.items()}}\n"
                "splits = {{name: manifest['records'] for name, manifest in dataset_manifests.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "write_dataset_csv(train_records, 'outputs/{stem}_train.csv')\n"
                "print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'reference': REFERENCE_GENOME, 'interval_bases': INTERVAL_BASES}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    by_label = {{label: round(sum(gc_content(r['sequence']) for r in splits[name] if r['label'] == label) / max(1, sum(1 for r in splits[name] if r['label'] == label)), 4) for label in (0, 1)}}\n"
                "    print({{name: {{'n': manifest['n_records'], 'labels': manifest['label_counts'], 'bases': manifest['bases'], 'gc_fraction': manifest['gc_fraction'], 'mean_gc_by_label': by_label, 'n_with_N': manifest['n_with_N'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "example = train_records[0]\n"
                "print({{'example': {{'id': example['id'], 'label': example['label'], 'region': example.get('region'), 'start': example.get('start'), 'end': example.get('end'), 'strand': example.get('strand'), 'sequence': example['sequence'][:60] + '...'}}}})\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in train_records[:8]],\n"
                "    'base outside A/C/G/T/N': [{{**train_records[0], 'sequence': train_records[0]['sequence'][:-1] + 'U'}}, *train_records[1:8]],\n"
                "    'too short': [{{**train_records[0], 'sequence': 'ACGTACG'}}, *train_records[1:8]],\n"
                "    'one label only': [{{**r, 'label': 1}} for r in train_records[:8]],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe, require_both_labels=True)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "## 5. Representations and masked prediction through the inference contract\n\n"
                "The inference contract is exercised as the representation-only tutorial exercised it. A deterministic "
                "in-code pair of 300-base sequences with **exactly the same multiset of bases** — one carrying the 6-mer "
                "`ATTCCG` four times, the other the same letters permuted — is embedded beside the first four held-out "
                "windows; identical composition means no GC rule can tell the pair apart, so the cosine distance between "
                "their vectors is a small look at what the representation carries beyond composition. `validate_inputs` "
                "applies exactly the checks `embed` applies (a list of A/C/G/T/N strings of 12..6,000 bases) and returns an "
                "input manifest with per-sequence SHA-256s; a sequence with a `U` is validated too and its rejection "
                "recorded as a finding. `embed` returns one 512-d **mean-pooled** vector per sequence — a representation, "
                "not a prediction; `token_counts` shows the 6-mer tokenisation (251 bases → 47 tokens); `predict_masked` "
                "returns the model's distribution at one masked position — its pre-training objective, which is what "
                "`<mask>` inside a repeated `ATTCCG` context should recover — and `predict` is refused until an adapter "
                "exists, which is the contract's point: the checkpoint is not a classifier."
            ),
            "code": (
                "import csv\n"
                "import random\n\n"
                "rng = random.Random(7)\n"
                "MOTIF = 'ATTCCG'\n"
                "filler = ''.join(rng.choice('ACGT') for _ in range(300 - 4 * len(MOTIF)))\n"
                "positions = sorted(rng.sample(range(0, len(filler), 30), 4))\n"
                "with_motif = ''\n"
                "cursor = 0\n"
                "for p in positions:\n"
                "    with_motif += filler[cursor:p] + MOTIF\n"
                "    cursor = p\n"
                "with_motif += filler[cursor:]\n"
                "permuted = list(with_motif)\n"
                "rng.shuffle(permuted)\n"
                "permuted = ''.join(permuted)\n"
                "assert sorted(with_motif) == sorted(permuted) and len(with_motif) == 300\n"
                "probe_sequences = [with_motif, permuted] + [r['sequence'] for r in test_records[:4]]\n"
                "probe_names = ['motif_x4', 'same_bases_permuted'] + [r['id'] for r in test_records[:4]]\n"
                "print({{'ceilings': {{'MIN_BASES': MIN_BASES, 'MAX_BASES': MAX_BASES, 'MAX_TOKENS': MAX_TOKENS, 'MAX_SEQUENCES': MAX_SEQUENCES, 'MIN_RECORDS': MIN_RECORDS, 'MAX_RECORDS': MAX_RECORDS, 'device': pipe.device, 'remote_code_executed': pipe.remote_code_executed}}}})\n"
                "input_manifest = validate_inputs(probe_sequences, names=probe_names)\n"
                "input_manifest['findings'] = []\n"
                "try:\n"
                "    validate_inputs(['ACGUACGUACGU'])\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'uracil-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'input_manifest': {{k: input_manifest[k] for k in ('n_sequences', 'bases', 'gc_fraction', 'n_with_N')}}, 'findings': len(input_manifest['findings'])}})\n\n"
                "t0 = time.perf_counter()\n"
                "vectors = pipe.embed(probe_sequences)\n"
                "embed_seconds = round(time.perf_counter() - t0, 3)\n"
                "counts = pipe.token_counts(probe_sequences)\n\n\n"
                "def cosine(a, b):\n"
                "    dot = sum(x * y for x, y in zip(a, b, strict=True))\n"
                "    return dot / ((sum(x * x for x in a) ** 0.5) * (sum(y * y for y in b) ** 0.5))\n\n\n"
                "pair_cosine = cosine(vectors[0], vectors[1])\n"
                "held_out_cosines = [round(cosine(vectors[0], v), 4) for v in vectors[2:]]\n"
                "checks = {{'one_vector_per_sequence': len(vectors) == len(probe_sequences), 'dimension': all(len(v) == HIDDEN_SIZE for v in vectors), 'pooling': POOLING}}\n"
                "if not all(v is True or isinstance(v, str) for v in checks.values()):\n"
                "    raise RuntimeError(f'embed output failed a sanity check: {{checks}}')\n"
                "print({{'embed': {{'n': len(vectors), 'dimension': len(vectors[0]), 'seconds': embed_seconds, 'tokens': dict(zip(probe_names, counts, strict=True)), 'checks': checks}}}})\n"
                "print({{'motif_vs_permuted_cosine': round(pair_cosine, 4), 'motif_vs_held_out_cosines': held_out_cosines, 'reading': 'same bases, different order: the distance between the pair is what the model carries beyond composition (sample-sanity, not a measurement)'}})\n"
                "with open('outputs/{stem}_embeddings.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.writer(handle)\n"
                "    writer.writerow(['name', 'bases', 'tokens'] + [f'dim_{{k}}' for k in range(HIDDEN_SIZE)])\n"
                "    for name, sequence, count, vector in zip(probe_names, probe_sequences, counts, vectors, strict=True):\n"
                "        writer.writerow([name, len(sequence), count] + [f'{{x:.6f}}' for x in vector])\n\n"
                "masked = pipe.predict_masked(MOTIF * 3 + '<mask>' + MOTIF * 3, top_k=5)\n"
                "print({{'masked_prediction': masked, 'reading': 'the pre-training objective: the distribution over 6-mers at the masked position'}})\n"
                "try:\n"
                "    pipe.predict(probe_sequences[:1])\n"
                "except RuntimeError as exc:\n"
                "    print({{'predict_before_adapt': 'refused', 'message': str(exc)}})"
            ),
        },
        {
            "md": (
                "## 6. Baselines and the frozen model on the held-out windows\n\n"
                "Three references frame the adaptation, each scored by `classification_metrics` (carried in `metrics.py`): "
                "**accuracy** and **MCC** — the Matthews correlation, 0 for any constant or chance predictor and symmetric "
                "in the two classes, which is the headline metric here — with per-class precision, recall and F1. The "
                "**majority** baseline answers the training majority label (0.5 on a balanced test split, MCC 0). The "
                "**GC-threshold** baseline is fitted on the training split alone — the midpoint threshold and direction "
                "that maximise training accuracy — and reads only composition: the build record measured **0.715 / 0.431** "
                "with the rule *GC ≥ 0.560 → promoter*, which is the honest floor for a sequence model on this task. The "
                "**frozen probe** (`pipe.linear_probe`) fits an L2-penalised logistic regression on the standardised "
                "mean-pooled embeddings of the training windows and scores the test windows; the model's weights are "
                "untouched, so this is what the pre-trained representation alone knows — the build record measured "
                "**0.815 / 0.632**. Expect the probe well above the GC rule: the representation carries more than "
                "composition. The cell asserts that ordering."
            ),
            "code": (
                "METRICS = ('accuracy', 'mcc')\n"
                "baseline_majority = majority_baseline(train_records, test_records)\n"
                "baseline_gc = gc_threshold_baseline(train_records, test_records)\n"
                "print({{'majority_baseline': {{k: baseline_majority[k] for k in METRICS}}, 'label': baseline_majority['label'], 'n': baseline_majority['n']}})\n"
                "print({{'gc_threshold_baseline': {{k: baseline_gc[k] for k in METRICS}}, 'threshold': baseline_gc['threshold'], 'rule': baseline_gc['rule'], 'train_accuracy': baseline_gc['train_accuracy']}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_probe = pipe.linear_probe(train_records, test_records)\n"
                "print({{'frozen_probe_test': {{k: frozen_probe[k] for k in METRICS}}, 'positive': frozen_probe['positive'], 'negative': frozen_probe['negative'], 'train_accuracy': frozen_probe['train_accuracy'], 'probe': frozen_probe['probe'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "assert frozen_probe['mcc'] > baseline_gc['mcc'] > baseline_majority['mcc']"
            ),
        },
        {
            "md": (
                "## 7. Bounded fine-tuning of the head and the last two blocks\n\n"
                "`pipe.adapt` builds a fresh **mean-pooled head** (a 512→512 `tanh` layer and a 512→2 output, 263,682 "
                "parameters, initialised from `SEED` so two runs start alike) and trains it together with the **last "
                "`TRAINED_LAYERS` encoder blocks** — two by default, 8,660,482 of 53.8 M parameters in all — while the "
                "embeddings and the first ten blocks stay frozen. Cross-entropy over the two labels, AdamW without weight "
                "decay at a fixed learning rate, gradient clipping at 1.0, batches of 16 in seeded order, no scheduler. Epoch "
                "0 records the untrained head's validation metrics (chance); every epoch is scored on the 200 validation "
                "windows and the epoch with the highest **validation MCC** is kept (ties: accuracy, then the earlier epoch); "
                "on any exception the frozen weights are restored.\n\n"
                "Watch the training loss fall from about 0.51 to 0.14 over six epochs while the validation MCC peaks early — "
                "the build record kept **epoch 2** (validation 0.805 / 0.621) and the later epochs were lower: 1,600 windows "
                "are enough to overfit two blocks, which is what the selection rule is for. The build record's "
                "counter-examples — the CLS-token head the upstream classification class uses (0.7725 / 0.552 on 640 "
                "windows, against 0.8275 / 0.658 for the mean-pooled head), four blocks (no better), and the whole encoder "
                "(0.83 / 0.686 but peaking at epoch 1 with a 200 MB adapter) — are why the default is two blocks under a "
                "mean-pooled head. Training is batched at a small learning rate, so the validation curve is noisy and the "
                "same recipe lands within a few hundredths of the numbers below from one GPU run to the next."
            ),
            "code": (
                "EPOCHS = 6  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 3e-5  # @param {{type:\"number\"}}\n"
                "TRAINED_LAYERS = DEFAULT_TRAINED_LAYERS  # @param {{type:\"integer\"}}\n"
                "SEED = 0  # @param {{type:\"integer\"}}\n\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row.update({{'val_accuracy': entry['val']['accuracy'], 'val_mcc': entry['val']['mcc']}})\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, layers=TRAINED_LAYERS, seed=SEED, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_parameters': adapt_result['n_trainable'], 'head_parameters': adapt_result['n_head'], 'total_parameters': adapt_result['n_total'], 'layers': adapt_result['layers'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'loss': adapt_result['loss'], 'train_accuracy': adapt_result['train_accuracy'], 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "## 8. Held-out evaluation\n\n"
                "The test windows were never used for training or epoch selection, and no sequence appears in two splits. "
                "The adapted model is scored by `pipe.evaluate` exactly as the probe and the baselines were in Section 6, the "
                "four systems are put side by side, and the per-class rows are read. Read it in this order: the **MCC** "
                "first (the build record measured 0.632 → **0.693**, past the GC rule's 0.431 and the majority's 0), then "
                "accuracy (0.815 → 0.8425), then the per-class rows — the adapted classifier is conservative on the promoter "
                "class (precision 0.905, recall 0.765) and permissive on the negatives (recall 0.92), which a threshold on "
                "the probabilities could trade but nothing here does. The cell asserts the adapted MCC is above the frozen "
                "probe's and above both baselines, and writes `evaluation_report` — the structured verdict — to "
                "`outputs/{stem}_evaluation_report.json`. Four hundred windows from one seeded draw give **no dispersion "
                "estimate**; the deltas are sample-sanity evidence that the adaptation contract works, not a benchmark, and "
                "a gain on this benchmark's window convention says nothing about promoters in *your* sequences until you "
                "measure it."
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records)\n"
                "adapted_val = pipe.evaluate(val_records)\n"
                "comparison = {{metric: {{'majority': baseline_majority[metric], 'gc_threshold': baseline_gc[metric], 'frozen_probe': frozen_probe[metric], 'adapted': adapted_test[metric]}} for metric in METRICS}}\n"
                "comparison['delta_vs_frozen_probe'] = {{metric: round(adapted_test[metric] - frozen_probe[metric], 4) for metric in METRICS}}\n"
                "comparison['delta_vs_gc_threshold'] = {{metric: round(adapted_test[metric] - baseline_gc[metric], 4) for metric in METRICS}}\n"
                "comparison['per_class'] = {{'frozen_probe': {{'positive': frozen_probe['positive'], 'negative': frozen_probe['negative']}}, 'adapted': {{'positive': adapted_test['positive'], 'negative': adapted_test['negative']}}}}\n"
                "comparison['confusion_adapted'] = adapted_test['confusion']\n"
                "for key, row in comparison.items():\n"
                "    print({{key: row}})\n"
                "verdict = evaluation_report(adapted_test, frozen_probe, [baseline_majority, baseline_gc], sample_kind='BYOD' if USE_BYOD else 'pinned promoter sample')\n"
                "print({{'verdict': verdict}})\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY, 'license': MODEL_LICENSE}},\n"
                "    'data_source': data_source,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'baselines': {{'majority': baseline_majority, 'gc_threshold': baseline_gc}},\n"
                "    'frozen_probe_test': frozen_probe,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'verdict': verdict,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "assert adapted_test['mcc'] > frozen_probe['mcc']\n"
                "assert verdict['adapted_beats_baselines']\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json', 'mcc_gain_over_frozen': verdict['mcc_gain_over_frozen']}})"
            ),
        },
        {
            "md": (
                "## 9. Look at the predictions, export the adapter and reload it\n\n"
                "Eight held-out windows are printed with their GC fraction, the GC rule's answer, the adapted "
                "classifier's label and promoter probability, and the truth — so the numbers can be checked by eye: look "
                "for windows the GC rule gets wrong that the classifier gets right, and for the probabilities near 0.5 "
                "that the accuracy hides. The pair from Section 5 is classified too (both are synthetic, so there is no "
                "truth — only the observation that identical composition can receive different probabilities).\n\n"
                "`pipe.save_artifact` writes the trained tensors — the head and the last two blocks, about 35 MB — as "
                "`adapter.safetensors`, with a `manifest.json` recording the artifact format, **the licence the adapter "
                "inherits (`cc-by-nc-sa-4.0`)**, the base model id and revision, the digest of the base `model.safetensors`, "
                "the two remote-code files the base executes, the tensor names, the file size and SHA-256, the training "
                "configuration and the epoch history (OUT8). `NucleotideTransformerPipeline.from_artifact` re-verifies "
                "the base snapshot (including the model code), checks the artifact manifest, its digest, its licence and "
                "its exact tensor set **before** deserialising, refuses any encoder tensor outside the recorded blocks, and "
                "overlays the tensors onto a freshly loaded base — a new object from files, not the in-memory model (VER2). "
                "The cell asserts identical labels and near-identical probabilities on 64 test windows (VER4)."
            ),
            "code": (
                "import shutil\n\n"
                "shown = test_records[:8]\n"
                "shown_predictions = pipe.predict([r['sequence'] for r in shown])\n"
                "for record, label, probabilities in zip(shown, shown_predictions['labels'], shown_predictions['probabilities'], strict=True):\n"
                "    gc = gc_content(record['sequence'])\n"
                "    gc_answer = int(gc >= baseline_gc['threshold']) if baseline_gc['rule'].startswith('GC >=') else int(gc < baseline_gc['threshold'])\n"
                "    print({{'id': record['id'], 'region': f\"{{record.get('region')}}:{{record.get('start')}}-{{record.get('end')}}{{record.get('strand', '')}}\", 'gc': round(gc, 3), 'gc_rule': gc_answer, 'adapted': label, 'p_promoter': probabilities[1], 'truth': record['label']}})\n"
                "pair = pipe.predict(probe_sequences[:2])\n"
                "print({{'synthetic_pair': dict(zip(probe_names[:2], [p[1] for p in pair['probabilities']], strict=True)), 'reading': 'same bases, different order; no truth exists for these'}})\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'license': artifact_manifest['license'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...', 'base_remote_code_files': artifact_manifest['base']['remote_code_files']}})\n\n"
                "reloaded = NucleotideTransformerPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "parity_sequences = [r['sequence'] for r in test_records[:64]]\n"
                "before = pipe.predict(parity_sequences)\n"
                "after = reloaded.predict(parity_sequences)\n"
                "parity = {{'identical_labels': sum(a == b for a, b in zip(before['labels'], after['labels'], strict=True)), 'of': len(parity_sequences), 'max_probability_difference': max(abs(x - y) for pa, pb in zip(before['probabilities'], after['probabilities'], strict=True) for x, y in zip(pa, pb, strict=True))}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch'], 'reloaded_layers': reloaded.adapter['layers']}})\n"
                "assert parity['identical_labels'] == parity['of'] and parity['max_probability_difference'] < 1e-4\n\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'remote_code': {{'executed': pipe.remote_code_executed, 'files': list(REMOTE_CODE_FILES), 'verified_before_import': True}},\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'total_bytes': snapshot.get('total_bytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHT_FILE, 'weight_format': 'safetensors, digest-verified', 'weight_sha256': pipe.weight_sha256}},\n"
                "    'data_source': data_source,\n"
                "    'corpus': {{'name': CORPUS_NAME, 'repo': CORPUS_REPO, 'revision': CORPUS_REVISION, 'dataset': CORPUS_DATASET, 'license': CORPUS_LICENSE, 'files': {{k: {{'bytes': v[0], 'sha256': v[1]}} for k, v in CORPUS_FILES.items()}}, 'reference': REFERENCE_GENOME, 'sample_digest': SAMPLE_DIGEST, 'split_digests': SAMPLE_SPLIT_DIGESTS}},\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'embedding_dimension': HIDDEN_SIZE, 'pooling': POOLING, 'motif_vs_permuted_cosine': round(pair_cosine, 6), 'masked_prediction': masked, 'output_files': ['outputs/{stem}_embeddings.csv', 'outputs/{stem}_input_manifest.json']}},\n"
                "    'comparison': comparison,\n"
                "    'verdict': verdict,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors']), 'license': artifact_manifest['license']}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32'}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "## Interpretation and limits\n\n"
        "A GC threshold fitted on the training windows classifies 71.5 % of the held-out windows (MCC 0.431), a logistic probe "
        "on the frozen mean-pooled embeddings 81.5 % (0.632), and a bounded fine-tuning of a mean-pooled head plus the last "
        "two encoder blocks on 1,600 windows 84.25 % (**0.693**), with a 35 MB adapter that reloads prediction-for-prediction "
        "and carries the base licence in its manifest. That is the claim: the adaptation contract works end to end on a "
        "real, licence-traced labelled set behind a verified remote-code perimeter, and the numbers it produces are read "
        "against two non-neural baselines and the frozen representation rather than in isolation.\n\n"
        "The test split is 400 windows from one seeded draw, the validation split that picks the epoch is 200, and the task "
        "is one benchmark's convention — 251-base windows centred on EPD non-TATA promoters against windows that contain "
        "none. So a gain here says the last two blocks learned that convention's promoter signal beyond composition, not "
        "that the classifier finds promoters in arbitrary sequence, handles TATA promoters or other species, or that its "
        "probabilities are calibrated (they are not; the per-class rows show a conservative promoter class). The 0.06 MCC "
        "gain over the frozen probe is a few times the run-to-run spread the build record observed, not a large margin, and "
        "the whole-encoder alternative that scores similarly peaks at epoch 1 and costs a 200 MB adapter — bounded is the "
        "point, not the ceiling.\n\n"
        "Three things to carry to real data. **Baselines first:** fit the GC rule and the frozen probe on *your* labels before "
        "reading any fine-tuned number; if the probe already matches the fine-tuning, the representation was the answer. "
        "**Labelling convention:** the windows the head learns from define what \"promoter\" means; keep the window length "
        "and the negative-sampling rule fixed between training and use, or the number means nothing. **Leakage:** keep every "
        "sequence in one split (the contract de-duplicates by exact bases) and split by chromosome or locus when windows "
        "overlap — the pinned sample inherits the origin's train/test separation, a BYOD CSV does not.\n\n"
        "Successful execution proves that the recorded repository revision's package, carried in this standalone notebook, can "
        "acquire and digest-verify the pinned model snapshot including the model code it executes, validate the demonstrated "
        "dataset contract without leakage on a licence-traced inline sample, execute the inference contract and a bounded "
        "fine-tuning, evaluate against two non-neural baselines and the frozen representation on a sequence-disjoint split, "
        "and emit the shown machine-readable artifacts — without the repository being reachable. It does **not** establish "
        "benchmark superiority, classification quality on any other task or window convention, calibration of the "
        "probabilities, or production fitness; and nothing it produces may be used commercially under the weights' "
        "licence.\n\n"
        "**Optional experiments (they do not affect the default path):** set `TRAINED_LAYERS = 0` and read how much of the "
        "gain the head alone recovers; set `TRAINED_LAYERS = 12` and watch the validation MCC peak at epoch 1 and the "
        "adapter grow to the whole encoder; raise `EPOCHS` and watch the selection rule keep an early epoch while the "
        "training loss keeps falling; or bring your own CSV through BYOD and read the two baselines before the adapted "
        "number.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/nucleotide-transformer-genomics-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/nucleotide-transformer-genomics-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance and the remote-code perimeter: https://github.com/kurtvalcorza/nucleotide-transformer-genomics-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code and licence: https://github.com/instadeepai/nucleotide-transformer (CC BY-NC-SA 4.0)\n"
        "- Nucleotide Transformer (Dalla-Torre et al., Nature Methods 2024): https://doi.org/10.1038/s41592-024-02523-z\n"
        "- Genomic Benchmarks (Grešová et al., BMC Genomic Data 2023; Apache-2.0): https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks — human non-TATA promoters from the Eukaryotic Promoter Database\n"
        "- GRCh38 reference genome via Ensembl REST: https://rest.ensembl.org/\n"
        "- DIMER Notebook Specification 2.0 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
